### ISSUE TITLE
APACHE_SPARK_VERSION must be >= 2.4.5 ? ; mirror.reverse.net is gone

### ISSUE THREAD

**Issue by readytheory** [jimthompson5802/spark-docker-cluster#3]
Thanks for making this.

APACHE_SPARK_VERSION you have 2.4.1, I think 2.4.5 is needed now.
And the server at reverse.net gives a permanently moved message now, I used:

    RUN curl -s  "http://www.trieuvan.com/apache/spark"/spark-2.4.5/spark-2.4.5-bin-hadoop2.7.tgz  | tar -xz -C /usr/local/

Some other GitBash (windows-specific) stuff, but got it going, very helpful project.

**Comment by jimthompson5802** [comment]
@readytheory   Thank you for pointing out the issue.  I'll look to update this in the future.

**Comment by readytheory** [comment]
I put a branch on my repo that runs without mods on windows GitBash, if you want me to send a PR let me know.

Again, thanks.  It's been a year and half since you put this together; would you advise a spark newbie that your repo (and mvillarrealb's original Medium article) are a reasonable starting point for getting one's hands dirty?  No major conceptual problems you've discovered since?

**Comment by jimthompson5802** [comment]
re:  would you advise a spark newbie that your repo (and mvillarrealb's original Medium article) are a reasonable starting point for getting one's hands dirty? 

Depends...if you're interested in learning PySpark programming, you can do that with a single node stand-alone cluster without the complications of this setup. I used the work in this repo as a way to gain some experience in running Spark inside Docker containers.  OTOH, if you're interested in leaning how to config Spark in a multi-node environment, then this repo  could be of some benefit.  The one thing missing is a more robust cluster manager, like YARN.

**Comment by readytheory** [comment]
Thank you again.
